pipeline
{
    agent any
    
    stages
    {
        stage("Build")
        {
            steps
            {
            echo("Build")
            }
        }
        
        stage("qa")
        {
            steps
            {
            echo("qa")
            }
        }
        
         
        stage("stage")
        {
            steps
            {
            echo("stage")
            }
        }
        
             
        stage("production")
        {
            steps
            {
            echo("production")
            }
        }
    } 
}